/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnectDomainRouteImport } from './routes/connect-domain'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DomainsRouteImport } from './routes/domains'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PlatformMatcherRouteImport } from './routes/platform-matcher'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectDomainRoute = ConnectDomainRouteImport.update({
  id: '/connect-domain',
  path: '/connect-domain',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsRoute = DomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformMatcherRoute = PlatformMatcherRouteImport.update({
  id: '/platform-matcher',
  path: '/platform-matcher',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect-domain': typeof ConnectDomainRoute
  '/dashboard': typeof DashboardRoute
  '/domains': typeof DomainsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/onboarding': typeof OnboardingRoute
  '/platform-matcher': typeof PlatformMatcherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect-domain': typeof ConnectDomainRoute
  '/dashboard': typeof DashboardRoute
  '/domains': typeof DomainsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/onboarding': typeof OnboardingRoute
  '/platform-matcher': typeof PlatformMatcherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect-domain': typeof ConnectDomainRoute
  '/dashboard': typeof DashboardRoute
  '/domains': typeof DomainsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/onboarding': typeof OnboardingRoute
  '/platform-matcher': typeof PlatformMatcherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect-domain'
    | '/dashboard'
    | '/domains'
    | '/how-it-works'
    | '/onboarding'
    | '/platform-matcher'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect-domain'
    | '/dashboard'
    | '/domains'
    | '/how-it-works'
    | '/onboarding'
    | '/platform-matcher'
  id:
    | '__root__'
    | '/'
    | '/connect-domain'
    | '/dashboard'
    | '/domains'
    | '/how-it-works'
    | '/onboarding'
    | '/platform-matcher'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectDomainRoute: typeof ConnectDomainRoute
  DashboardRoute: typeof DashboardRoute
  DomainsRoute: typeof DomainsRoute
  HowItWorksRoute: typeof HowItWorksRoute
  OnboardingRoute: typeof OnboardingRoute
  PlatformMatcherRoute: typeof PlatformMatcherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect-domain': {
      id: '/connect-domain'
      path: '/connect-domain'
      fullPath: '/connect-domain'
      preLoaderRoute: typeof ConnectDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains': {
      id: '/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform-matcher': {
      id: '/platform-matcher'
      path: '/platform-matcher'
      fullPath: '/platform-matcher'
      preLoaderRoute: typeof PlatformMatcherRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectDomainRoute: ConnectDomainRoute,
  DashboardRoute: DashboardRoute,
  DomainsRoute: DomainsRoute,
  HowItWorksRoute: HowItWorksRoute,
  OnboardingRoute: OnboardingRoute,
  PlatformMatcherRoute: PlatformMatcherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
